### ISSUE TITLE
Dataset Division

### ISSUE THREAD

**Issue by TZYSJTU** [cvlab-yonsei/dkn#3]
The authors provided a data divison in google cloud. However, When I use the official NYU_v2 dataset to train the model I get a much worse result. I want to know how the authors divide the data. This is suspicious.

**Comment by jun0kim** [comment]
I used the same image pairs as "Deep Joint Image Filtering, ECCV 2016'".
The first 1,000 images are used for train, and the rest are for test. 
Compare the images one by one yourself with official NYU_v2 dataset, If you think that is suspicious.
